[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv

lib_deps = 
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^6.21.5
  fastled/FastLED@^3.6.0
  https://github.com/schreibfaul1/ESP32-audioI2S.git
  me-no-dev/ESP Async WebServer@^1.2.4
  me-no-dev/AsyncTCP@^1.1.1

build_flags = 
  -DCORE_DEBUG_LEVEL=1
  -DMQTT_MAX_PACKET_SIZE=1024
