[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = partitions.csv

build_unflags = -std=gnu++20
build_flags = -std=gnu++2a -fpermissive

lib_deps =
    ESP32-audioI2S
    esp32async/ESPAsyncWebServer
    esp32async/AsyncTCP
    tzapu/WiFiManager
    FastLED
    ArduinoJson
    PubSubClient

# Configuração do Monitor Serial
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
