[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = partitions.csv
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.psram_type = opi

build_unflags = -std=gnu++20
build_flags = 
    -std=gnu++2a 
    -fpermissive
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0
    -Iinclude

lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.8
    esp32async/ESPAsyncWebServer
    esp32async/AsyncTCP
    tzapu/WiFiManager
    FastLED
    ArduinoJson
    PubSubClient

# Configuração do Monitor Serial
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
